### ISSUE TITLE
Need functionalities to access projects

### ISSUE THREAD

**Issue by ypzheng** [ypzheng/Build-System-Inference#12]
Since we need to read the files under certain project directory, we need to write easier methods to import a project or access certain project directory.

**Comment by theLauA** [comment]
You mean list/search files under project directory?

**Comment by juconghe** [comment]
I think a had written a method to search for a list of files, but deleted on Tuesday.  Just need to dig through the git history to take it back

**Comment by theLauA** [comment]
It is resolved already. 
In Ultility.class, lsdirectory and lsdorectoryrs will do the job.
