### ISSUE TITLE
PathParser only parses propreties from .properties file

### ISSUE THREAD

**Issue by ypzheng** [ypzheng/Build-System-Inference#2]
For inferring the four directories:
We need PathParser to be able to check if the path we are looking for are listed on top of the build file, or if they are listed on explicit .properties file.  

Ultimately, we need to be able to get the full directory path.

**Comment by theLauA** [comment]
I will work on this.
Current idea:
For local properties -> store them in a list or a dictionary
For .properties files -> load them using java properties class's load method
