### ISSUE TITLE
Some build files contains multiple javac's

### ISSUE THREAD

**Issue by ypzheng** [ypzheng/Build-System-Inference#4]
There are more than one directory of source files/compiled classes under one single "compile" target.  We need to get those, too?

**Comment by theLauA** [comment]
Maybe we should update the interface so that the method return a list(Vector/array) of String.

**Comment by theLauA** [comment]
On second thought we can just output a string in form "dir_1 ; dir_2 ; dir_3 ".

**Comment by ypzheng** [comment]
All set for now.
