### ISSUE TITLE
Need method(s) that execute targets

### ISSUE THREAD

**Issue by ypzheng** [ypzheng/Build-System-Inference#6]
In order to obtain a list of dependencies and tests, we need to execute the targets that compile the sources and tests (this part is already done).

**Comment by juconghe** [comment]
Had a working demo on my other computer. Push that later today.

**Comment by juconghe** [comment]
We don't need a method to execute the target. We can simply call the `target.execute()` within the Target class. However, we need to find the correct order of executing the Targets. Which I still don't know the exact way if a build file is so messy.

**Comment by ypzheng** [comment]
We might not need to execute the target.  If we can get a directory that contains dependencies, we can just get those filenames.  Similarly, we can also obtain a list of test classes if we can get a directory that contains xx/xx/**Test.java.  What do you think?
